Repository NU-WA-Project/BE, pull requests merged in 2024-03, with the labels that each got.

#34 File & Chat fix
  deploy.sh
  src/main/java/org/project/nuwabackend/api/FileController.java
  src/main/java/org/project/nuwabackend/api/WorkSpaceController.java
  src/main/java/org/project/nuwabackend/api/channel/DirectChannelController.java
  src/main/java/org/project/nuwabackend/api/message/DirectMessageController.java
  src/main/java/org/project/nuwabackend/domain/multimedia/File.java
  src/main/java/org/project/nuwabackend/domain/workspace/WorkSpaceMember.java
  src/main/java/org/project/nuwabackend/dto/channel/response/DirectChannelListResponseDto.java
  src/main/java/org/project/nuwabackend/dto/file/request/FileRequestDto.java
  src/main/java/org/project/nuwabackend/dto/file/response/FileInfoResponseDto.java
  src/main/java/org/project/nuwabackend/dto/file/response/FileUploadResponseDto.java
  src/main/java/org/project/nuwabackend/dto/file/response/FileUrlResponseDto.java
  src/main/java/org/project/nuwabackend/dto/file/response/TopSevenFileInfoResponseDto.java
  src/main/java/org/project/nuwabackend/dto/workspace/response/FavoriteWorkSpaceMemberInfoResponse.java
  src/main/java/org/project/nuwabackend/global/type/SuccessMessage.java
  src/main/java/org/project/nuwabackend/repository/jpa/DirectChannelRepository.java
  src/main/java/org/project/nuwabackend/service/WorkSpaceService.java
  src/main/java/org/project/nuwabackend/service/channel/DirectChannelService.java
  src/main/java/org/project/nuwabackend/service/message/DirectMessageQueryService.java
  src/main/java/org/project/nuwabackend/service/message/DirectMessageService.java
  src/main/java/org/project/nuwabackend/service/s3/FileQueryService.java
  src/main/java/org/project/nuwabackend/service/s3/FileService.java
  src/main/java/org/project/nuwabackend/service/s3/S3Service.java
  src/main/java/org/project/nuwabackend/type/FilePathType.java
  src/main/java/org/project/nuwabackend/type/FileType.java
  src/main/java/org/project/nuwabackend/type/FileUploadType.java
  src/main/java/org/project/nuwabackend/type/NotificationType.java
  src/main/java/org/project/nuwabackend/type/WorkSpaceMemberType.java
  src/test/java/org/project/nuwabackend/api/FileControllerTest.java
  src/test/java/org/project/nuwabackend/api/channel/DirectChannelControllerTest.java
  src/test/java/org/project/nuwabackend/domain/multimedia/FileTest.java
  src/test/java/org/project/nuwabackend/service/channel/DirectChannelServiceTest.java
  src/test/java/org/project/nuwabackend/service/s3/FileServiceTest.java
  src/test/java/org/project/nuwabackend/service/s3/S3ServiceTest.java
Labels: documentation, enhancement

#35 Feature/inquirymail
  build.gradle
  src/main/java/org/project/nuwabackend/api/InquiryEmailController.java
  src/main/java/org/project/nuwabackend/api/WorkSpaceController.java
  src/main/java/org/project/nuwabackend/domain/Inquire.java
  src/main/java/org/project/nuwabackend/dto/InquireIdResponse.java
  src/main/java/org/project/nuwabackend/dto/IntroductionInquiryMailRequestDto.java
  src/main/java/org/project/nuwabackend/dto/ServiceInquiryMailRequestDto.java
  src/main/java/org/project/nuwabackend/global/type/ErrorMessage.java
  src/main/java/org/project/nuwabackend/global/type/SuccessMessage.java
  src/main/java/org/project/nuwabackend/service/MailService.java
  src/main/resources/application.yml
  src/main/resources/facebook.png
  src/main/resources/instagram.png
  src/main/resources/kakaotalk.png
  src/main/resources/nuwalogo.png
Labels: documentation, enhancement

#36 Feature/invitationlink
  src/main/java/org/project/nuwabackend/api/InvitationLinkController.java
  src/main/java/org/project/nuwabackend/domain/redis/InvitationLinkRedis.java
  src/main/java/org/project/nuwabackend/dto/InvitationLinkRequest.java
  src/main/java/org/project/nuwabackend/dto/InvitationLinkResponse.java
  src/main/java/org/project/nuwabackend/global/type/ErrorMessage.java
  src/main/java/org/project/nuwabackend/global/type/SuccessMessage.java
  src/main/java/org/project/nuwabackend/repository/jpa/WorkSpaceMemberRepository.java
  src/main/java/org/project/nuwabackend/repository/redis/InvitationLinkRedisRepository.java
  src/main/java/org/project/nuwabackend/service/InvitationLinkService.java
Labels: enhancement

#39 Add messageType
  .github/workflows/deploy.yml
  deploy.sh
  src/main/java/org/project/nuwabackend/api/WorkSpaceController.java
  src/main/java/org/project/nuwabackend/api/channel/ChatChannelController.java
  src/main/java/org/project/nuwabackend/api/channel/DirectChannelController.java
  src/main/java/org/project/nuwabackend/config/jwt/JwtAuthFilter.java
  src/main/java/org/project/nuwabackend/config/websocket/StompInterceptor.java
  src/main/java/org/project/nuwabackend/domain/mongo/ChatMessage.java
  src/main/java/org/project/nuwabackend/domain/mongo/DirectMessage.java
  src/main/java/org/project/nuwabackend/domain/redis/ChatChannelRedis.java
  src/main/java/org/project/nuwabackend/dto/channel/response/ChatChannelListResponseDto.java
  src/main/java/org/project/nuwabackend/dto/message/request/ChatMessageRequestDto.java
  src/main/java/org/project/nuwabackend/dto/message/request/DirectMessageRequestDto.java
  src/main/java/org/project/nuwabackend/dto/message/response/ChatMessageListResponseDto.java
  src/main/java/org/project/nuwabackend/dto/message/response/ChatMessageResponseDto.java
  src/main/java/org/project/nuwabackend/dto/message/response/DirectMessageResponseDto.java
  src/main/java/org/project/nuwabackend/global/type/ErrorMessage.java
  src/main/java/org/project/nuwabackend/global/type/SuccessMessage.java
  src/main/java/org/project/nuwabackend/repository/jpa/ChatChannelRepository.java
  src/main/java/org/project/nuwabackend/repository/jpa/WorkSpaceMemberRepository.java
  src/main/java/org/project/nuwabackend/repository/redis/ChannelRedisService.java
  src/main/java/org/project/nuwabackend/repository/redis/ChatChannelRedisRepository.java
  src/main/java/org/project/nuwabackend/service/channel/ChatChannelRedisService.java
  src/main/java/org/project/nuwabackend/service/channel/ChatChannelService.java
  src/main/java/org/project/nuwabackend/service/channel/DirectChannelRedisService.java
  src/main/java/org/project/nuwabackend/service/message/ChatMessageService.java
  src/main/java/org/project/nuwabackend/service/message/DirectMessageService.java
  src/main/java/org/project/nuwabackend/service/workspace/WorkSpaceMemberQueryService.java
  src/main/java/org/project/nuwabackend/service/workspace/WorkSpaceService.java
  src/main/java/org/project/nuwabackend/type/MessageType.java
  src/test/java/org/project/nuwabackend/api/WorkSpaceControllerTest.java
  src/test/java/org/project/nuwabackend/api/message/DirectMessageControllerTest.java
  src/test/java/org/project/nuwabackend/domain/mongo/DirectMessageTest.java
  src/test/java/org/project/nuwabackend/service/WorkSpaceServiceTest.java
  src/test/java/org/project/nuwabackend/service/channel/DirectChannelRedisServiceTest.java
  src/test/java/org/project/nuwabackend/service/channel/DirectChannelServiceTest.java
  src/test/java/org/project/nuwabackend/service/message/ChatMessageServiceTest.java
  src/test/java/org/project/nuwabackend/service/message/DirectMessageServiceTest.java
Labels: documentation, enhancement

#41 채팅 & 워크스페이스 API 수정 및 생성
  src/main/java/org/project/nuwabackend/api/WorkSpaceController.java
  src/main/java/org/project/nuwabackend/api/channel/ChatChannelController.java
  src/main/java/org/project/nuwabackend/api/channel/DirectChannelController.java
  src/main/java/org/project/nuwabackend/api/channel/VoiceChannelController.java
  src/main/java/org/project/nuwabackend/api/message/ChatMessageController.java
  src/main/java/org/project/nuwabackend/domain/redis/ChatChannelRedis.java
  src/main/java/org/project/nuwabackend/dto/channel/request/ChatChannelJoinMemberRequest.java
  src/main/java/org/project/nuwabackend/dto/channel/request/ChatChannelJoinMemberRequestDto.java
  src/main/java/org/project/nuwabackend/dto/channel/request/DirectChannelRequest.java
  src/main/java/org/project/nuwabackend/dto/channel/request/DirectChannelRequestDto.java
  src/main/java/org/project/nuwabackend/dto/channel/request/VoiceChannelJoinMemberRequest.java
  src/main/java/org/project/nuwabackend/dto/channel/request/VoiceChannelJoinMemberRequestDto.java
  src/main/java/org/project/nuwabackend/dto/channel/request/VoiceChannelRequest.java
  src/main/java/org/project/nuwabackend/dto/channel/request/VoiceChannelRequestDto.java
  src/main/java/org/project/nuwabackend/dto/channel/response/ChatChannelRoomIdResponse.java
  src/main/java/org/project/nuwabackend/dto/channel/response/ChatChannelRoomIdResponseDto.java
  src/main/java/org/project/nuwabackend/dto/channel/response/DirectChannelInfoResponseDto.java
  src/main/java/org/project/nuwabackend/dto/channel/response/DirectChannelListResponse.java
  src/main/java/org/project/nuwabackend/dto/channel/response/DirectChannelListResponseDto.java
  src/main/java/org/project/nuwabackend/dto/channel/response/DirectChannelRoomIdResponse.java
  src/main/java/org/project/nuwabackend/dto/channel/response/DirectChannelRoomIdResponseDto.java
  src/main/java/org/project/nuwabackend/dto/channel/response/VoiceChannelIdResponse.java
  src/main/java/org/project/nuwabackend/dto/channel/response/VoiceChannelIdResponseDto.java
  src/main/java/org/project/nuwabackend/dto/workspace/response/FavoriteWorkSpaceMemberInfoResponse.java
  src/main/java/org/project/nuwabackend/dto/workspace/response/FavoriteWorkSpaceMemberInfoResponseDto.java
  src/main/java/org/project/nuwabackend/dto/workspace/response/IndividualWorkSpaceMemberInfoResponse.java
  src/main/java/org/project/nuwabackend/dto/workspace/response/IndividualWorkSpaceMemberInfoResponseDto.java
  src/main/java/org/project/nuwabackend/global/type/SuccessMessage.java
  src/main/java/org/project/nuwabackend/repository/jpa/DirectChannelRepository.java
  src/main/java/org/project/nuwabackend/service/channel/ChatChannelRedisService.java
  src/main/java/org/project/nuwabackend/service/channel/ChatChannelService.java
  src/main/java/org/project/nuwabackend/service/channel/DirectChannelService.java
  src/main/java/org/project/nuwabackend/service/channel/VoiceChannelService.java
  src/main/java/org/project/nuwabackend/service/message/DirectMessageQueryService.java
  src/main/java/org/project/nuwabackend/service/workspace/WorkSpaceService.java
  src/main/resources/application-sentry.yml
  src/test/java/org/project/nuwabackend/api/WorkSpaceControllerTest.java
  src/test/java/org/project/nuwabackend/api/channel/ChatChannelControllerTest.java
  src/test/java/org/project/nuwabackend/api/channel/DirectChannelControllerTest.java
  src/test/java/org/project/nuwabackend/domain/redis/ChatChannelRedisTest.java
  src/test/java/org/project/nuwabackend/service/WorkSpaceServiceTest.java
  src/test/java/org/project/nuwabackend/service/channel/ChatChannelRedisServiceTest.java
  src/test/java/org/project/nuwabackend/service/channel/ChatChannelServiceTest.java
  src/test/java/org/project/nuwabackend/service/channel/DirectChannelServiceTest.java
Labels: documentation, enhancement

#43 Delete API
  build.gradle
  src/main/java/org/project/nuwabackend/api/ChannelAndMessageDeleteController.java
  src/main/java/org/project/nuwabackend/api/FileAndMessageController.java
  src/main/java/org/project/nuwabackend/api/FileController.java
  src/main/java/org/project/nuwabackend/api/channel/DirectChannelController.java
  src/main/java/org/project/nuwabackend/api/workspace/WorkSpaceController.java
  src/main/java/org/project/nuwabackend/api/workspace/WorkSpaceDeleteController.java
  src/main/java/org/project/nuwabackend/domain/channel/Direct.java
  src/main/java/org/project/nuwabackend/domain/workspace/WorkSpace.java
  src/main/java/org/project/nuwabackend/domain/workspace/WorkSpaceMember.java
  src/main/java/org/project/nuwabackend/dto/channel/response/DirectChannelInfoResponseDto.java
  src/main/java/org/project/nuwabackend/dto/workspace/response/IndividualWorkSpaceMemberInfoResponseDto.java
  src/main/java/org/project/nuwabackend/dto/workspace/response/WorkSpaceInfoResponse.java
  src/main/java/org/project/nuwabackend/global/type/ErrorMessage.java
  src/main/java/org/project/nuwabackend/global/type/SuccessMessage.java
  src/main/java/org/project/nuwabackend/repository/jpa/ChannelRepository.java
  src/main/java/org/project/nuwabackend/repository/jpa/ChatChannelRepository.java
  src/main/java/org/project/nuwabackend/repository/jpa/DirectChannelRepository.java
  src/main/java/org/project/nuwabackend/repository/jpa/FileRepository.java
  src/main/java/org/project/nuwabackend/repository/jpa/WorkSpaceMemberRepository.java
  src/main/java/org/project/nuwabackend/repository/jpa/WorkSpaceRepository.java
  src/main/java/org/project/nuwabackend/repository/jpa/notification/NotificationRepository.java
  src/main/java/org/project/nuwabackend/service/InvitationLinkService.java
  src/main/java/org/project/nuwabackend/service/channel/ChannelAndMessageDeleteService.java
  src/main/java/org/project/nuwabackend/service/channel/ChatChannelService.java
  src/main/java/org/project/nuwabackend/service/channel/DirectChannelRedisService.java
  src/main/java/org/project/nuwabackend/service/channel/DirectChannelService.java
  src/main/java/org/project/nuwabackend/service/message/ChatMessageQueryService.java
  src/main/java/org/project/nuwabackend/service/message/DirectMessageQueryService.java
  src/main/java/org/project/nuwabackend/service/notification/NotificationService.java
  src/main/java/org/project/nuwabackend/service/s3/FileAndMessageDeleteService.java
  src/main/java/org/project/nuwabackend/service/s3/FileService.java
  src/main/java/org/project/nuwabackend/service/s3/S3Service.java
  src/main/java/org/project/nuwabackend/service/workspace/WorkSpaceDeleteService.java
  src/main/java/org/project/nuwabackend/service/workspace/WorkSpaceMemberQueryService.java
  src/main/java/org/project/nuwabackend/service/workspace/WorkSpaceService.java
  src/main/java/org/project/nuwabackend/type/FilePathType.java
  src/main/java/org/project/nuwabackend/type/FileType.java
  src/main/java/org/project/nuwabackend/type/NotificationType.java
  src/test/java/org/project/nuwabackend/api/WorkSpaceControllerTest.java
  src/test/java/org/project/nuwabackend/api/channel/DirectChannelControllerTest.java
  src/test/java/org/project/nuwabackend/domain/workspace/WorkSpaceTest.java
  src/test/java/org/project/nuwabackend/service/WorkSpaceServiceTest.java
  src/test/java/org/project/nuwabackend/service/channel/DirectChannelServiceTest.java
  src/test/java/org/project/nuwabackend/service/message/DirectMessageQueryServiceTest.java
Labels: documentation, enhancement

#45 Test delete api
  src/main/java/org/project/nuwabackend/api/ChannelAndMessageDeleteController.java
  src/main/java/org/project/nuwabackend/api/FileAndMessageController.java
  src/main/java/org/project/nuwabackend/api/FileController.java
  src/main/java/org/project/nuwabackend/api/channel/ChatChannelController.java
  src/main/java/org/project/nuwabackend/api/message/DirectMessageController.java
  src/main/java/org/project/nuwabackend/api/workspace/WorkSpaceController.java
  src/main/java/org/project/nuwabackend/api/workspace/WorkSpaceDeleteController.java
  src/main/java/org/project/nuwabackend/config/websocket/StompInterceptor.java
  src/main/java/org/project/nuwabackend/dto/file/response/FileUploadResponseDto.java
  src/main/java/org/project/nuwabackend/global/type/SuccessMessage.java
  src/main/java/org/project/nuwabackend/service/channel/ChannelAndMessageDeleteService.java
  src/main/java/org/project/nuwabackend/service/channel/ChatChannelService.java
  src/main/java/org/project/nuwabackend/service/channel/DirectChannelRedisService.java
  src/main/java/org/project/nuwabackend/service/channel/DirectChannelService.java
  src/main/java/org/project/nuwabackend/service/message/ChatMessageQueryService.java
  src/main/java/org/project/nuwabackend/service/message/DirectMessageService.java
  src/main/java/org/project/nuwabackend/service/notification/NotificationService.java
  src/main/java/org/project/nuwabackend/service/s3/FileAndMessageDeleteService.java
  src/main/java/org/project/nuwabackend/service/s3/FileService.java
  src/main/java/org/project/nuwabackend/service/s3/S3Service.java
  src/main/java/org/project/nuwabackend/service/workspace/WorkSpaceDeleteService.java
  src/main/java/org/project/nuwabackend/service/workspace/WorkSpaceService.java
  src/main/java/org/project/nuwabackend/type/MessageType.java
  src/test/java/org/project/nuwabackend/api/FileControllerTest.java
  src/test/java/org/project/nuwabackend/service/WorkSpaceServiceTest.java
  src/test/java/org/project/nuwabackend/service/channel/DirectChannelServiceTest.java
  src/test/java/org/project/nuwabackend/service/s3/FileServiceTest.java
  src/test/java/org/project/nuwabackend/service/s3/S3ServiceTest.java
Labels: documentation, enhancement

#46 Feature/emails3
  src/main/java/org/project/nuwabackend/service/MailService.java
Labels: documentation, enhancement

#47 Update, Delete Message Api
  src/main/java/org/project/nuwabackend/api/FileController.java
  src/main/java/org/project/nuwabackend/api/message/ChatMessageController.java
  src/main/java/org/project/nuwabackend/api/message/DirectMessageController.java
  src/main/java/org/project/nuwabackend/domain/mongo/ChatMessage.java
  src/main/java/org/project/nuwabackend/domain/mongo/DirectMessage.java
  src/main/java/org/project/nuwabackend/dto/message/request/MessageDeleteRequestDto.java
  src/main/java/org/project/nuwabackend/dto/message/request/MessageUpdateRequestDto.java
  src/main/java/org/project/nuwabackend/dto/message/response/ChatMessageListResponseDto.java
  src/main/java/org/project/nuwabackend/dto/message/response/ChatMessageResponseDto.java
  src/main/java/org/project/nuwabackend/dto/message/response/DirectMessageResponseDto.java
  src/main/java/org/project/nuwabackend/dto/message/response/MessageDeleteResponseDto.java
  src/main/java/org/project/nuwabackend/dto/message/response/MessageUpdateResponseDto.java
  src/main/java/org/project/nuwabackend/service/message/ChatMessageQueryService.java
  src/main/java/org/project/nuwabackend/service/message/ChatMessageService.java
  src/main/java/org/project/nuwabackend/service/message/DirectMessageQueryService.java
  src/main/java/org/project/nuwabackend/service/message/DirectMessageService.java
  src/main/java/org/project/nuwabackend/type/MessageType.java
Labels: documentation, enhancement

#48 Feature/update api
  src/main/java/org/project/nuwabackend/api/NotificationController.java
  src/main/java/org/project/nuwabackend/config/SecurityConfig.java
  src/main/java/org/project/nuwabackend/domain/channel/Channel.java
  src/main/java/org/project/nuwabackend/domain/channel/Chat.java
  src/main/java/org/project/nuwabackend/domain/channel/Direct.java
  src/main/java/org/project/nuwabackend/domain/channel/Voice.java
  src/main/java/org/project/nuwabackend/domain/notification/Notification.java
  src/main/java/org/project/nuwabackend/global/type/ErrorMessage.java
  src/main/java/org/project/nuwabackend/global/type/SuccessMessage.java
  src/main/java/org/project/nuwabackend/service/notification/NotificationService.java
Labels: documentation, enhancement

#49 :recycle: update email conf (starttls : true)
  src/main/resources/application.yml
Labels: documentation, enhancement

#50 :recycle: encode tokens in Base64
  src/main/java/org/project/nuwabackend/service/InvitationLinkService.java
Labels: documentation, enhancement

#51 Feature/bug fix
  src/main/java/org/project/nuwabackend/api/FileAndMessageController.java
  src/main/java/org/project/nuwabackend/api/message/DirectMessageController.java
  src/main/java/org/project/nuwabackend/domain/notification/Notification.java
  src/main/java/org/project/nuwabackend/dto/notification/response/NotificationListResponseDto.java
  src/main/java/org/project/nuwabackend/dto/notification/response/NotificationResponseDto.java
  src/main/java/org/project/nuwabackend/service/message/ChatMessageService.java
  src/main/java/org/project/nuwabackend/service/message/DirectMessageService.java
  src/main/java/org/project/nuwabackend/service/notification/NotificationQueryService.java
  src/main/java/org/project/nuwabackend/service/notification/NotificationService.java
  src/main/java/org/project/nuwabackend/service/workspace/WorkSpaceService.java
  src/main/resources/facebook.png
  src/main/resources/instagram.png
  src/main/resources/kakaotalk.png
  src/main/resources/nuwalogo.png
  src/test/java/org/project/nuwabackend/domain/notification/NotificationTest.java
  src/test/java/org/project/nuwabackend/service/WorkSpaceServiceTest.java
  src/test/java/org/project/nuwabackend/service/message/ChatMessageServiceTest.java
  src/test/java/org/project/nuwabackend/service/message/DirectMessageServiceTest.java
Labels: documentation, enhancement

#52 :sparkles: app rawString & server time format Asia/Seoul
  src/main/java/org/project/nuwabackend/NuwaBackendApplication.java
  src/main/java/org/project/nuwabackend/domain/mongo/ChatMessage.java
  src/main/java/org/project/nuwabackend/domain/mongo/DirectMessage.java
  src/main/java/org/project/nuwabackend/domain/notification/Notification.java
  src/main/java/org/project/nuwabackend/dto/message/request/ChatMessageRequestDto.java
  src/main/java/org/project/nuwabackend/dto/message/request/DirectMessageRequestDto.java
  src/main/java/org/project/nuwabackend/dto/message/response/ChatMessageListResponseDto.java
  src/main/java/org/project/nuwabackend/dto/message/response/ChatMessageResponseDto.java
  src/main/java/org/project/nuwabackend/dto/message/response/DirectMessageResponseDto.java
  src/main/java/org/project/nuwabackend/service/channel/DirectChannelService.java
  src/main/java/org/project/nuwabackend/service/message/ChatMessageService.java
  src/main/java/org/project/nuwabackend/service/message/DirectMessageService.java
  src/main/java/org/project/nuwabackend/service/notification/NotificationService.java
  src/main/java/org/project/nuwabackend/type/MessageType.java
  src/test/java/org/project/nuwabackend/domain/mongo/DirectMessageTest.java
  src/test/java/org/project/nuwabackend/service/channel/DirectChannelServiceTest.java
  src/test/java/org/project/nuwabackend/service/message/ChatMessageServiceTest.java
  src/test/java/org/project/nuwabackend/service/message/DirectMessageServiceTest.java
Labels: documentation, enhancement

#53 delete message & notification group data return
  src/main/java/org/project/nuwabackend/api/FileAndMessageController.java
  src/main/java/org/project/nuwabackend/api/NotificationController.java
  src/main/java/org/project/nuwabackend/dto/notification/request/NotificationIdListRequestDto.java
  src/main/java/org/project/nuwabackend/dto/notification/response/NotificationGroupResponseDto.java
  src/main/java/org/project/nuwabackend/dto/notification/response/NotificationListResponseDto.java
  src/main/java/org/project/nuwabackend/dto/notification/response/NotificationResponseDto.java
  src/main/java/org/project/nuwabackend/repository/jpa/FileRepository.java
  src/main/java/org/project/nuwabackend/repository/jpa/notification/NotificationRepository.java
  src/main/java/org/project/nuwabackend/service/channel/DirectChannelService.java
  src/main/java/org/project/nuwabackend/service/message/ChatMessageQueryService.java
  src/main/java/org/project/nuwabackend/service/message/DirectMessageQueryService.java
  src/main/java/org/project/nuwabackend/service/notification/NotificationQueryService.java
  src/main/java/org/project/nuwabackend/service/notification/NotificationService.java
  src/main/java/org/project/nuwabackend/service/s3/FileAndMessageDeleteService.java
  src/main/java/org/project/nuwabackend/service/s3/FileService.java
Labels: documentation, enhancement

#54 Feature/notification read
  src/main/java/org/project/nuwabackend/api/NotificationController.java
  src/main/java/org/project/nuwabackend/api/auth/AuthController.java
  src/main/java/org/project/nuwabackend/api/channel/ChatChannelController.java
  src/main/java/org/project/nuwabackend/api/message/DirectMessageController.java
  src/main/java/org/project/nuwabackend/config/websocket/StompInterceptor.java
  src/main/java/org/project/nuwabackend/domain/channel/ChatJoinMember.java
  src/main/java/org/project/nuwabackend/domain/channel/VoiceJoinMember.java
  src/main/java/org/project/nuwabackend/domain/member/Member.java
  src/main/java/org/project/nuwabackend/domain/mongo/Canvas.java
  src/main/java/org/project/nuwabackend/domain/mongo/ChatMessage.java
  src/main/java/org/project/nuwabackend/domain/mongo/DirectMessage.java
  src/main/java/org/project/nuwabackend/dto/channel/response/ChatChannelInfoResponseDto.java
  src/main/java/org/project/nuwabackend/dto/channel/response/DirectChannelInfoResponseDto.java
  src/main/java/org/project/nuwabackend/dto/channel/response/DirectChannelResponseDto.java
  src/main/java/org/project/nuwabackend/dto/message/response/ChatMessageListResponseDto.java
  src/main/java/org/project/nuwabackend/dto/message/response/ChatMessageResponseDto.java
  src/main/java/org/project/nuwabackend/global/type/SuccessMessage.java
  src/main/java/org/project/nuwabackend/repository/jpa/ChatChannelRepository.java
  src/main/java/org/project/nuwabackend/repository/jpa/DirectChannelRepository.java
  src/main/java/org/project/nuwabackend/repository/jpa/notification/NotificationRepository.java
  src/main/java/org/project/nuwabackend/repository/mongo/CanvasRepository.java
  src/main/java/org/project/nuwabackend/service/auth/LoginService.java
  src/main/java/org/project/nuwabackend/service/channel/ChannelAndMessageDeleteService.java
  src/main/java/org/project/nuwabackend/service/channel/ChatChannelService.java
  src/main/java/org/project/nuwabackend/service/channel/DirectChannelService.java
  src/main/java/org/project/nuwabackend/service/message/ChatMessageService.java
  src/main/java/org/project/nuwabackend/service/notification/NotificationService.java
  src/main/java/org/project/nuwabackend/service/workspace/WorkSpaceMemberQueryService.java
  src/test/java/org/project/nuwabackend/service/channel/DirectChannelServiceTest.java
  src/test/java/org/project/nuwabackend/service/message/ChatMessageServiceTest.java
Labels: documentation, enhancement

#55 Feature/canvas
  src/main/java/org/project/nuwabackend/api/CanvasController.java
  src/main/java/org/project/nuwabackend/config/websocket/StompInterceptor.java
  src/main/java/org/project/nuwabackend/config/websocket/WebSocketConfig.java
  src/main/java/org/project/nuwabackend/domain/mongo/Canvas.java
  src/main/java/org/project/nuwabackend/dto/canvas/request/CanvasRequestDto.java
  src/main/java/org/project/nuwabackend/dto/canvas/response/CanvasResponseDto.java
  src/main/java/org/project/nuwabackend/dto/message/response/DirectMessageResponseDto.java
  src/main/java/org/project/nuwabackend/global/type/ErrorMessage.java
  src/main/java/org/project/nuwabackend/global/type/SuccessMessage.java
  src/main/java/org/project/nuwabackend/repository/jpa/WorkSpaceMemberRepository.java
  src/main/java/org/project/nuwabackend/repository/jpa/notification/NotificationRepository.java
  src/main/java/org/project/nuwabackend/repository/mongo/CanvasRepository.java
  src/main/java/org/project/nuwabackend/service/CanvasQueryService.java
  src/main/java/org/project/nuwabackend/service/CanvasService.java
  src/main/java/org/project/nuwabackend/service/message/ChatMessageQueryService.java
  src/main/java/org/project/nuwabackend/service/message/ChatMessageService.java
  src/main/java/org/project/nuwabackend/service/message/DirectMessageQueryService.java
  src/main/java/org/project/nuwabackend/service/message/DirectMessageService.java
  src/main/java/org/project/nuwabackend/service/notification/NotificationService.java
  src/main/java/org/project/nuwabackend/type/NotificationType.java
Labels: documentation, enhancement

#56 :sparkles: InvitationLink By Mail API
  src/main/java/org/project/nuwabackend/api/InvitationLinkController.java
  src/main/java/org/project/nuwabackend/dto/InviteByMailRequest.java
  src/main/java/org/project/nuwabackend/global/type/SuccessMessage.java
  src/main/java/org/project/nuwabackend/service/InvitationLinkService.java
Labels: duplicate, enhancement

#57 :bug: fix_v1
  src/main/java/org/project/nuwabackend/domain/channel/Channel.java
  src/main/java/org/project/nuwabackend/dto/channel/response/ChatChannelInfoResponseDto.java
  src/main/java/org/project/nuwabackend/service/channel/ChatChannelService.java
  src/main/java/org/project/nuwabackend/service/workspace/WorkSpaceSearchQueryService.java
Labels: documentation, enhancement

#58 canvas search & file search & workspace content search
  src/main/java/org/project/nuwabackend/api/CanvasController.java
  src/main/java/org/project/nuwabackend/api/InquiryEmailController.java
  src/main/java/org/project/nuwabackend/api/InvitationLinkController.java
  src/main/java/org/project/nuwabackend/api/channel/ChatChannelController.java
  src/main/java/org/project/nuwabackend/api/workspace/WorkSpaceContentSearchController.java
  src/main/java/org/project/nuwabackend/dto/InquireIdResponse.java
  src/main/java/org/project/nuwabackend/dto/file/response/FileInfoResponseDto.java
  src/main/java/org/project/nuwabackend/dto/file/response/FileSearchInfoResponseDto.java
  src/main/java/org/project/nuwabackend/dto/inquiry/request/IntroductionInquiryMailRequestDto.java
  src/main/java/org/project/nuwabackend/dto/inquiry/request/ServiceInquiryMailRequestDto.java
  src/main/java/org/project/nuwabackend/dto/inquiry/response/InquireIdResponse.java
  src/main/java/org/project/nuwabackend/dto/invite/request/InvitationLinkRequest.java
  src/main/java/org/project/nuwabackend/dto/invite/request/InviteByMailRequest.java
  src/main/java/org/project/nuwabackend/dto/invite/response/InvitationLinkResponse.java
  src/main/java/org/project/nuwabackend/dto/workspace/response/WorkSpaceContentSearchResponseDto.java
  src/main/java/org/project/nuwabackend/global/type/ErrorMessage.java
  src/main/java/org/project/nuwabackend/global/type/SuccessMessage.java
  src/main/java/org/project/nuwabackend/repository/jpa/FileRepository.java
  src/main/java/org/project/nuwabackend/repository/mongo/CanvasRepository.java
  src/main/java/org/project/nuwabackend/service/InvitationLinkService.java
  src/main/java/org/project/nuwabackend/service/MailService.java
  src/main/java/org/project/nuwabackend/service/canvas/CanvasQueryService.java
  src/main/java/org/project/nuwabackend/service/canvas/CanvasService.java
  src/main/java/org/project/nuwabackend/service/s3/FileQueryService.java
  src/main/java/org/project/nuwabackend/service/s3/FileService.java
  src/main/java/org/project/nuwabackend/service/workspace/WorkSpaceContentSearchService.java
  src/main/java/org/project/nuwabackend/service/workspace/WorkSpaceSearchQueryService.java
Labels: documentation, enhancement

#59 delete api (chat, direct, workspace)
  src/main/java/org/project/nuwabackend/api/ChannelAndMessageDeleteController.java
  src/main/java/org/project/nuwabackend/api/channel/ChatChannelController.java
  src/main/java/org/project/nuwabackend/api/workspace/WorkSpaceController.java
  src/main/java/org/project/nuwabackend/api/workspace/WorkSpaceDeleteController.java
  src/main/java/org/project/nuwabackend/config/SecurityConfig.java
  src/main/java/org/project/nuwabackend/config/handler/CustomAuthenticationFailureHandler.java
  src/main/java/org/project/nuwabackend/config/handler/CustomAuthenticationSuccessHandler.java
  src/main/java/org/project/nuwabackend/domain/channel/Channel.java
  src/main/java/org/project/nuwabackend/domain/channel/Chat.java
  src/main/java/org/project/nuwabackend/domain/channel/ChatJoinMember.java
  src/main/java/org/project/nuwabackend/domain/channel/Direct.java
  src/main/java/org/project/nuwabackend/domain/channel/Voice.java
  src/main/java/org/project/nuwabackend/domain/workspace/WorkSpace.java
  src/main/java/org/project/nuwabackend/dto/channel/response/ChatChannelListResponseDto.java
  src/main/java/org/project/nuwabackend/global/type/ErrorMessage.java
  src/main/java/org/project/nuwabackend/global/type/SuccessMessage.java
  src/main/java/org/project/nuwabackend/repository/jpa/ChatChannelRepository.java
  src/main/java/org/project/nuwabackend/repository/jpa/ChatJoinMemberRepository.java
  src/main/java/org/project/nuwabackend/repository/jpa/DirectChannelRepository.java
  src/main/java/org/project/nuwabackend/service/InvitationLinkService.java
  src/main/java/org/project/nuwabackend/service/channel/ChannelAndMessageDeleteService.java
  src/main/java/org/project/nuwabackend/service/channel/ChatChannelService.java
  src/main/java/org/project/nuwabackend/service/channel/DirectChannelService.java
  src/main/java/org/project/nuwabackend/service/workspace/WorkSpaceDeleteService.java
  src/main/java/org/project/nuwabackend/service/workspace/WorkSpaceService.java
  src/test/java/org/project/nuwabackend/api/channel/ChatChannelControllerTest.java
  src/test/java/org/project/nuwabackend/service/channel/ChatChannelServiceTest.java
Labels: documentation, enhancement

#60 :sparkles: canvas api by workspace, workspace member auth change api
  src/main/java/org/project/nuwabackend/api/CanvasController.java
  src/main/java/org/project/nuwabackend/api/workspace/WorkSpaceController.java
  src/main/java/org/project/nuwabackend/global/type/ErrorMessage.java
  src/main/java/org/project/nuwabackend/service/canvas/CanvasQueryService.java
  src/main/java/org/project/nuwabackend/service/canvas/CanvasService.java
  src/main/java/org/project/nuwabackend/service/workspace/WorkSpaceService.java
  src/test/java/org/project/nuwabackend/service/WorkSpaceServiceTest.java
Labels: documentation, enhancement
